apiVersion: v1
kind: Service
metadata:
  name: fafsa-web
  namespace: fafsa-assistant
  labels:
    app.kubernetes.io/name: fafsa-web
    app.kubernetes.io/component: web
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: fafsa-web
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: fafsa-web-pdb
  namespace: fafsa-assistant
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: fafsa-web
